# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Brute Force method(exhaustive search) to solve knapsack problem in C++
#' @param set_of_weight weights
#' @param set_of_profit profits
#' @param W_max maximum weight
#' @param R_number passed from R
#' @return A list with optimal value and selected elements
#' @export
bruteforce_knapsack <- function(set_of_weight, set_of_profit, W_max, R_number) {
    .Call('_Lab6_bruteforce_knapsack', PACKAGE = 'Lab6', set_of_weight, set_of_profit, W_max, R_number)
}

