# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bruteforce_knapsack <- function(set_of_weight, set_of_profit, W_max, R_number) {
    .Call('_Lab6_bruteforce_knapsack', PACKAGE = 'Lab6', set_of_weight, set_of_profit, W_max, R_number)
}

